/* eslint-disable */
// Generated by apps/api/scripts/export_openapi_contract.py.
// Do not edit manually.

export interface components {
  schemas: {
    "AddBlockToTemplateRequest": {
      "block_id": string
      "condition_field"?: string | null
      "is_optional"?: boolean
      "overrides"?: Record<string, unknown> | null
      "position": number
    }
    "ApprovalRequestDetailResponse": {
      "created_at": string
      "id": string
      "lot_id": string
      "organization_id": string
      "payload": Record<string, unknown>
      "request_type"?: string
      "status": string
      "vendor_id": string
      "vendor_name": string
      "vendor_phone"?: string | null
      "vendor_platform": string
    }
    "BotResponse": {
      "bot_username": string
      "is_active": boolean
    }
    "ConnectRequest": {
      "credentials": string
      "display_name": string
      "organization_id": string
      "provider": string
      "scopes"?: Array<string> | null
      "server_url"?: string | null
      "user_id": string
    }
    "CreateBlockRequest": {
      "category": string
      "content": string
      "created_by"?: string | null
      "name": string
      "organization_id": string
      "tags"?: Array<string> | null
      "variables"?: Array<string> | null
    }
    "CreateTemplateRequest": {
      "created_by"?: string | null
      "description"?: string | null
      "document_type": string
      "footer_config"?: Record<string, unknown> | null
      "header_config"?: Record<string, unknown> | null
      "name": string
      "organization_id": string
      "page_config"?: Record<string, unknown> | null
    }
    "CreateVersionRequest": {
      "author_id"?: string | null
      "change_note"?: string | null
      "content": string
    }
    "DecisionRequest": {
      "action": string
      "admin_id": string
      "organization_id": string
    }
    "DecisionResponse": {
      "error"?: string | null
      "success": boolean
    }
    "DocumentEvidenceResponse": {
      "bbox"?: Record<string, unknown> | null
      "chunk_index"?: number | null
      "confidence"?: number | null
      "created_at"?: string | null
      "id": string
      "legal_document_id": string
      "legal_document_page_id"?: string | null
      "organization_id": string
      "project_id": string
      "snippet"?: string | null
      "snippet_hash": string
      "variable_resolution_id": string
    }
    "DocumentVariablesGroup": {
      "comprador"?: Record<string, unknown>
      "lote"?: Record<string, unknown>
      "mandato"?: Record<string, unknown>
      "matriz"?: Record<string, unknown>
      "personeria"?: Record<string, unknown>
      "sag"?: Record<string, unknown>
      "servidumbre"?: Record<string, unknown>
      "transaccion"?: Record<string, unknown>
      "vendedor"?: Record<string, unknown>
    }
    "EscrituraCaseCreateRequest": {
      "created_by"?: string | null
      "organization_id": string
      "project_id": string
      "warning_acknowledged"?: boolean
    }
    "EscrituraCaseSnapshotResponse": {
      "case_status": string
      "escritura_case_id": string
      "evidence_snapshot_count": number
      "readiness_status": string
      "variable_snapshot_count": number
    }
    "EscrituraReadinessResponse": {
      "evidence_snapshot"?: Record<string, unknown>
      "gates"?: Array<components["schemas"]["ReadinessGateResponse"]>
      "lot_id": string
      "organization_id": string
      "project_id": string
      "readiness_status": string
      "variable_snapshot"?: Record<string, unknown>
    }
    "GenerateRequest": {
      "document_type"?: string
      "format"?: "pdf" | "docx"
      "generated_by"?: string | null
      "lot_id": string
      "missing_variables_accepted"?: boolean
      "organization_id": string
      "selected_recipients"?: Array<"vendedor" | "comprador">
      "template_id": string
    }
    "GenerateResponse": {
      "document_id": string
      "document_type": string
      "file_url": string
      "format": "pdf" | "docx"
      "lot_id": string
      "missing_variables_accepted": boolean
      "selected_recipients"?: Array<string>
      "template_id": string
      "version_number": number
    }
    "HTTPValidationError": {
      "detail"?: Array<components["schemas"]["ValidationError"]>
    }
    "InvalidateCacheRequest": {
      "organization_id": string
    }
    "LegalDocumentListResponse": {
      "documents"?: Array<components["schemas"]["LegalDocumentResponse"]>
      "project_id"?: string | null
    }
    "LegalDocumentRegisterRequest": {
      "document_type": string
      "file_size_bytes": number
      "lot_id"?: string | null
      "mime_type": string
      "organization_id": string
      "original_filename": string
      "project_id": string
      "sha256_hash": string
      "source_field"?: string | null
      "storage_bucket"?: string
      "storage_path": string
      "upload_source"?: string
      "uploaded_by"?: string | null
    }
    "LegalDocumentRegistrationQueuedResponse": {
      "extraction_status": string
      "ingestion_job_id": string
      "legal_document_id": string
      "version_number": number
    }
    "LegalDocumentResponse": {
      "created_at"?: string | null
      "document_type": string
      "extraction_status": string
      "file_size_bytes": number
      "id": string
      "lot_id"?: string | null
      "mime_type": string
      "organization_id": string
      "original_filename": string
      "project_id": string
      "sha256_hash"?: string | null
      "source_field"?: string | null
      "storage_bucket": string
      "storage_path": string
      "superseded_by"?: string | null
      "updated_at"?: string | null
      "upload_source": string
      "uploaded_by"?: string | null
      "version_number"?: number
    }
    "LegalDocumentRetryResponse": {
      "attempt_number": number
      "extraction_status": string
      "ingestion_job_id": string
      "legal_document_id": string
    }
    "LotLegalDataResponse": {
      "created_at"?: string | null
      "id": string
      "lot_id": string
      "matching_score"?: number | null
      "matching_status": string
      "organization_id": string
      "project_id": string
      "reviewed_at"?: string | null
      "reviewed_by"?: string | null
      "role_status": string
      "sii_definitive_role"?: string | null
      "sii_pre_role"?: string | null
      "sii_role_in_process_text"?: string | null
      "sii_role_matrix"?: string | null
      "sii_unit_name"?: string | null
      "source_legal_document_id"?: string | null
      "updated_at"?: string | null
    }
    "MarkReadResponse": {
      "read_at": string
      "success": boolean
    }
    "MetaChange": {
      "field": string
      "value": components["schemas"]["MetaValue"]
    }
    "MetaContact": {
      "profile": Record<string, unknown>
      "wa_id": string
    }
    "MetaEntry": {
      "changes": Array<components["schemas"]["MetaChange"]>
      "id": string
    }
    "MetaMessage": {
      "from": string
      "id": string
      "text"?: components["schemas"]["MetaText"] | null
      "timestamp": string
      "type"?: "text" | "image" | "audio" | "document" | "interactive" | "button" | "unknown"
    }
    "MetaText": {
      "body": string
    }
    "MetaValue": {
      "contacts"?: Array<components["schemas"]["MetaContact"]> | null
      "messages"?: Array<components["schemas"]["MetaMessage"]> | null
      "messaging_product": string
      "metadata": Record<string, unknown>
      "statuses"?: Array<Record<string, unknown>> | null
    }
    "MetaWebhookPayload": {
      "entry": Array<components["schemas"]["MetaEntry"]>
      "object": string
    }
    "NotificationCounts": {
      "approved": number
      "pending": number
      "rejected": number
      "unread": number
    }
    "NotificationDecisionRequest": {
      "action": "approve" | "reject"
      "approval_id": string
    }
    "NotificationDecisionResponse": {
      "code"?: string | null
      "error"?: string | null
      "status"?: string | null
      "success": boolean
    }
    "NotificationItem": {
      "approval_id": string
      "can_decide": boolean
      "client_name": string
      "created_at": string
      "decided_at"?: string | null
      "id": string
      "lot_label": string
      "project_name": string
      "read_at"?: string | null
      "request_type": string
      "status": string
      "vendor_name": string
    }
    "NotificationListResponse": {
      "counts": components["schemas"]["NotificationCounts"]
      "items": Array<components["schemas"]["NotificationItem"]>
    }
    "PreviewRequest": {
      "lot_id": string
      "organization_id": string
      "template_id": string
    }
    "PreviewResponse": {
      "html": string
    }
    "ReadinessGateResponse": {
      "blocking_variables"?: Array<string>
      "gate": string
      "status": string
      "warnings"?: Array<string>
    }
    "RegisterBotRequest": {
      "bot_token": string
      "organization_id": string
    }
    "ReservationPayload": {
      "cliente_nombre": string
      "cliente_run": string
      "fecha_firma"?: string | null
      "notaria"?: string | null
      "valor_reserva": number
    }
    "ReservationRequest": {
      "lot_id": string
      "organization_id": string
      "payload": components["schemas"]["ReservationPayload"]
      "vendor_id": string
      "vendor_name": string
      "vendor_phone": string
      "vendor_platform": string
    }
    "ReservationResponse": {
      "approval_id": string
      "message"?: string
      "status"?: string
    }
    "RoleManualOverrideRequest": {
      "matching_status"?: string
      "reason": string
      "reviewed_by"?: string | null
      "role_status": string
      "sii_definitive_role"?: string | null
      "sii_pre_role"?: string | null
      "sii_role_in_process_text"?: string | null
      "sii_role_matrix"?: string | null
      "sii_unit_name"?: string | null
      "source_legal_document_id"?: string | null
    }
    "RoleMatchingInventoryResponse": {
      "lots"?: Array<components["schemas"]["LotLegalDataResponse"]>
      "project_id": string
      "summary"?: Record<string, number>
    }
    "SalePayload": {
      "cliente_nombre": string
      "cliente_run": string
      "fecha_firma"?: string | null
      "notaria"?: string | null
      "valor_final": number
    }
    "SaleRequest": {
      "lot_id": string
      "organization_id": string
      "payload": components["schemas"]["SalePayload"]
      "previous_lot_state"?: "disponible" | "reservado" | null
      "sale_mode"?: "direct" | "reserved" | null
      "vendor_id": string
      "vendor_name": string
      "vendor_phone": string
      "vendor_platform": string
    }
    "SandboxRequest": {
      "organization_id": string
      "prompt_content": string
      "test_message": string
    }
    "TelegramTokenRequest": {
      "organization_id"?: string | null
      "profile_id": string
    }
    "TelegramTokenResponse": {
      "bot_username": string
      "deep_link": string
      "token": string
    }
    "UpdateBlockRequest": {
      "category"?: string | null
      "content"?: string | null
      "is_active"?: boolean | null
      "name"?: string | null
      "tags"?: Array<string> | null
      "variables"?: Array<string> | null
    }
    "ValidationError": {
      "ctx"?: Record<string, unknown>
      "input"?: unknown
      "loc": Array<string | number>
      "msg": string
      "type": string
    }
    "VariableInventoryResponse": {
      "groups"?: Record<string, Array<components["schemas"]["VariableResolutionResponse"]>>
      "lot_id"?: string | null
      "project_id": string
      "summary"?: Record<string, number>
    }
    "VariableResolutionResponse": {
      "approval_required"?: boolean
      "confidence"?: number | null
      "correction_reason"?: string | null
      "created_at"?: string | null
      "escritura_case_id"?: string | null
      "evidence"?: Array<components["schemas"]["DocumentEvidenceResponse"]>
      "extractor_name"?: string | null
      "id": string
      "lot_id"?: string | null
      "organization_id": string
      "project_id": string
      "reviewed_at"?: string | null
      "reviewed_by"?: string | null
      "source_ref"?: Record<string, unknown>
      "source_type": string
      "state": string
      "superseded_by"?: string | null
      "updated_at"?: string | null
      "value_json"?: Record<string, unknown> | Array<unknown> | null
      "value_text"?: string | null
      "variable_group": string
      "variable_key": string
    }
    "VariableReviewResponse": {
      "audit_event_id": string
      "reviewed_at"?: string | null
      "reviewed_by"?: string | null
      "state": string
      "variable_resolution_id": string
    }
    "VariableStatusResponse": {
      "available"?: Array<string>
      "missing"?: Array<string>
      "sources"?: Record<string, string>
      "variables": components["schemas"]["DocumentVariablesGroup"]
    }
    "VariableUpdateRequest": {
      "action": string
      "correction_reason"?: string | null
      "evidence_ids"?: Array<string>
      "evidence_policy"?: string
      "reviewed_by"?: string | null
      "state"?: string | null
      "value_json"?: Record<string, unknown> | Array<unknown> | null
      "value_text"?: string | null
    }
  }
}

export interface operations {
  "requestReservationApproval": {
    method: "POST"
    path: "/api/v1/approvals/request-reservation"
    requestBody: components["schemas"]["ReservationRequest"]
    response: components["schemas"]["ReservationResponse"]
  }
  "requestSaleApproval": {
    method: "POST"
    path: "/api/v1/approvals/request-sale"
    requestBody: components["schemas"]["SaleRequest"]
    response: components["schemas"]["ReservationResponse"]
  }
  "getApprovalRequest": {
    method: "GET"
    path: "/api/v1/approvals/{approval_id}"
    requestBody: never
    response: components["schemas"]["ApprovalRequestDetailResponse"]
  }
  "decideApprovalRequest": {
    method: "POST"
    path: "/api/v1/approvals/{approval_id}/decide"
    requestBody: components["schemas"]["DecisionRequest"]
    response: components["schemas"]["DecisionResponse"]
  }
  "register_bot_api_v1_bots_register_post": {
    method: "POST"
    path: "/api/v1/bots/register"
    requestBody: components["schemas"]["RegisterBotRequest"]
    response: components["schemas"]["BotResponse"]
  }
  "delete_bot_api_v1_bots__org_id__delete": {
    method: "DELETE"
    path: "/api/v1/bots/{org_id}"
    requestBody: never
    response: void
  }
  "get_bot_api_v1_bots__org_id__get": {
    method: "GET"
    path: "/api/v1/bots/{org_id}"
    requestBody: never
    response: components["schemas"]["BotResponse"] | null
  }
  "list_blocks_api_v1_documents_blocks_get": {
    method: "GET"
    path: "/api/v1/documents/blocks"
    requestBody: never
    response: Array<Record<string, unknown>>
  }
  "create_block_api_v1_documents_blocks_post": {
    method: "POST"
    path: "/api/v1/documents/blocks"
    requestBody: components["schemas"]["CreateBlockRequest"]
    response: Record<string, unknown>
  }
  "update_block_api_v1_documents_blocks__block_id__put": {
    method: "PUT"
    path: "/api/v1/documents/blocks/{block_id}"
    requestBody: components["schemas"]["UpdateBlockRequest"]
    response: Record<string, unknown>
  }
  "generateDocument": {
    method: "POST"
    path: "/api/v1/documents/generate"
    requestBody: components["schemas"]["GenerateRequest"]
    response: components["schemas"]["GenerateResponse"]
  }
  "list_generated_documents_api_v1_documents_generated_get": {
    method: "GET"
    path: "/api/v1/documents/generated"
    requestBody: never
    response: Array<Record<string, unknown>>
  }
  "previewDocument": {
    method: "POST"
    path: "/api/v1/documents/preview"
    requestBody: components["schemas"]["PreviewRequest"]
    response: components["schemas"]["PreviewResponse"]
  }
  "list_templates_api_v1_documents_templates_get": {
    method: "GET"
    path: "/api/v1/documents/templates"
    requestBody: never
    response: Array<Record<string, unknown>>
  }
  "create_template_api_v1_documents_templates_post": {
    method: "POST"
    path: "/api/v1/documents/templates"
    requestBody: components["schemas"]["CreateTemplateRequest"]
    response: Record<string, unknown>
  }
  "get_template_blocks_api_v1_documents_templates__template_id__blocks_get": {
    method: "GET"
    path: "/api/v1/documents/templates/{template_id}/blocks"
    requestBody: never
    response: Array<Record<string, unknown>>
  }
  "add_block_to_template_api_v1_documents_templates__template_id__blocks_post": {
    method: "POST"
    path: "/api/v1/documents/templates/{template_id}/blocks"
    requestBody: components["schemas"]["AddBlockToTemplateRequest"]
    response: Record<string, unknown>
  }
  "remove_block_from_template_api_v1_documents_templates__template_id__blocks__item_id__delete": {
    method: "DELETE"
    path: "/api/v1/documents/templates/{template_id}/blocks/{item_id}"
    requestBody: never
    response: void
  }
  "get_variables_api_v1_documents_variables__lot_id__get": {
    method: "GET"
    path: "/api/v1/documents/variables/{lot_id}"
    requestBody: never
    response: components["schemas"]["VariableStatusResponse"]
  }
  "create_escritura_case_api_v1_escritura_cases_lots__lot_id__post": {
    method: "POST"
    path: "/api/v1/escritura-cases/lots/{lot_id}"
    requestBody: components["schemas"]["EscrituraCaseCreateRequest"]
    response: components["schemas"]["EscrituraCaseSnapshotResponse"]
  }
  "get_escritura_readiness_api_v1_escritura_cases_lots__lot_id__readiness_get": {
    method: "GET"
    path: "/api/v1/escritura-cases/lots/{lot_id}/readiness"
    requestBody: never
    response: components["schemas"]["EscrituraReadinessResponse"]
  }
  "health_check_api_v1_health_get": {
    method: "GET"
    path: "/api/v1/health"
    requestBody: never
    response: Record<string, string>
  }
  "list_integrations_api_v1_integrations__get": {
    method: "GET"
    path: "/api/v1/integrations/"
    requestBody: never
    response: void
  }
  "connect_integration_api_v1_integrations_connect_post": {
    method: "POST"
    path: "/api/v1/integrations/connect"
    requestBody: components["schemas"]["ConnectRequest"]
    response: void
  }
  "revoke_integration_api_v1_integrations__connection_id__delete": {
    method: "DELETE"
    path: "/api/v1/integrations/{connection_id}"
    requestBody: never
    response: void
  }
  "test_integration_api_v1_integrations__connection_id__test_post": {
    method: "POST"
    path: "/api/v1/integrations/{connection_id}/test"
    requestBody: never
    response: void
  }
  "list_project_legal_documents_api_v1_legal_documents_project__project_id__get": {
    method: "GET"
    path: "/api/v1/legal-documents/project/{project_id}"
    requestBody: never
    response: components["schemas"]["LegalDocumentListResponse"]
  }
  "register_legal_document_api_v1_legal_documents_register_post": {
    method: "POST"
    path: "/api/v1/legal-documents/register"
    requestBody: components["schemas"]["LegalDocumentRegisterRequest"]
    response: components["schemas"]["LegalDocumentRegistrationQueuedResponse"]
  }
  "retry_legal_document_ingestion_api_v1_legal_documents__legal_document_id__retry_post": {
    method: "POST"
    path: "/api/v1/legal-documents/{legal_document_id}/retry"
    requestBody: never
    response: components["schemas"]["LegalDocumentRetryResponse"]
  }
  "update_lot_legal_role_api_v1_legal_roles_lots__lot_id__patch": {
    method: "PATCH"
    path: "/api/v1/legal-roles/lots/{lot_id}"
    requestBody: components["schemas"]["RoleManualOverrideRequest"]
    response: components["schemas"]["LotLegalDataResponse"]
  }
  "get_project_legal_roles_api_v1_legal_roles_project__project_id__matches_get": {
    method: "GET"
    path: "/api/v1/legal-roles/project/{project_id}/matches"
    requestBody: never
    response: components["schemas"]["RoleMatchingInventoryResponse"]
  }
  "get_project_legal_variables_api_v1_legal_variables_project__project_id__get": {
    method: "GET"
    path: "/api/v1/legal-variables/project/{project_id}"
    requestBody: never
    response: components["schemas"]["VariableInventoryResponse"]
  }
  "update_legal_variable_api_v1_legal_variables__variable_resolution_id__patch": {
    method: "PATCH"
    path: "/api/v1/legal-variables/{variable_resolution_id}"
    requestBody: components["schemas"]["VariableUpdateRequest"]
    response: components["schemas"]["VariableReviewResponse"]
  }
  "listNotifications": {
    method: "GET"
    path: "/api/v1/notifications/"
    requestBody: never
    response: components["schemas"]["NotificationListResponse"]
  }
  "decideNotificationApproval": {
    method: "POST"
    path: "/api/v1/notifications/{approval_id}/decide"
    requestBody: components["schemas"]["NotificationDecisionRequest"]
    response: components["schemas"]["NotificationDecisionResponse"]
  }
  "markNotificationRead": {
    method: "POST"
    path: "/api/v1/notifications/{notification_id}/read"
    requestBody: never
    response: components["schemas"]["MarkReadResponse"]
  }
  "list_prompts_api_v1_prompts__get": {
    method: "GET"
    path: "/api/v1/prompts/"
    requestBody: never
    response: void
  }
  "sandbox_prompt_api_v1_prompts_sandbox_post": {
    method: "POST"
    path: "/api/v1/prompts/sandbox"
    requestBody: components["schemas"]["SandboxRequest"]
    response: void
  }
  "activate_version_api_v1_prompts__prompt_id__activate__version_id__put": {
    method: "PUT"
    path: "/api/v1/prompts/{prompt_id}/activate/{version_id}"
    requestBody: never
    response: void
  }
  "list_versions_api_v1_prompts__prompt_id__versions_get": {
    method: "GET"
    path: "/api/v1/prompts/{prompt_id}/versions"
    requestBody: never
    response: void
  }
  "create_version_api_v1_prompts__prompt_id__versions_post": {
    method: "POST"
    path: "/api/v1/prompts/{prompt_id}/versions"
    requestBody: components["schemas"]["CreateVersionRequest"]
    response: void
  }
  "invalidate_cache_api_v1_skills_invalidate_cache_post": {
    method: "POST"
    path: "/api/v1/skills/invalidate-cache"
    requestBody: components["schemas"]["InvalidateCacheRequest"]
    response: void
  }
  "generate_telegram_vincule_token_api_v1_users_telegram_token_post": {
    method: "POST"
    path: "/api/v1/users/telegram-token"
    requestBody: components["schemas"]["TelegramTokenRequest"]
    response: components["schemas"]["TelegramTokenResponse"]
  }
  "verify_meta_webhook_api_v1_webhook_meta_get": {
    method: "GET"
    path: "/api/v1/webhook/meta"
    requestBody: never
    response: void
  }
  "receive_meta_webhook_api_v1_webhook_meta_post": {
    method: "POST"
    path: "/api/v1/webhook/meta"
    requestBody: components["schemas"]["MetaWebhookPayload"]
    response: void
  }
  "receive_telegram_webhook_api_v1_webhook_telegram__org_id__post": {
    method: "POST"
    path: "/api/v1/webhook/telegram/{org_id}"
    requestBody: never
    response: void
  }
}

export type OperationRequestBody<K extends keyof operations> = operations[K]["requestBody"]
export type OperationResponse<K extends keyof operations> = operations[K]["response"]
