/* eslint-disable */
// Generated by apps/api/scripts/export_openapi_contract.py.
// Do not edit manually.

export interface components {
  schemas: {
    "AddBlockToTemplateRequest": {
      "block_id": string
      "condition_field"?: string | null
      "is_optional"?: boolean
      "overrides"?: Record<string, unknown> | null
      "position": number
    }
    "Adquirente": {
      "cuota"?: string | null
      "nombre"?: components["schemas"]["EvidencedValue"] | null
    }
    "Antecesor": {
      "nombre"?: components["schemas"]["EvidencedValue"] | null
    }
    "ApprovalBlocker": {
      "action_href"?: string | null
      "action_label"?: string | null
      "alert_tipo"?: string | null
      "cause"?: string | null
      "description"?: string | null
      "fix_url"?: string | null
      "gate"?: string | null
      "key"?: string | null
      "kind": "token_missing" | "readiness_gate" | "alert_clause_missing" | "snapshot_stale"
      "message"?: string | null
      "required_clause"?: string | null
      "title"?: string | null
    }
    "ApprovalRequestDetailResponse": {
      "created_at": string
      "id": string
      "lot_id": string
      "organization_id": string
      "payload": Record<string, unknown>
      "request_type"?: string
      "status": string
      "vendor_id": string
      "vendor_name": string
      "vendor_phone"?: string | null
      "vendor_platform": string
    }
    "BlockResolution": {
      "blockKey": string
      "label"?: string | null
      "status": "resolved" | "missing" | "blocked"
      "text"?: string | null
    }
    "BotResponse": {
      "bot_username": string
      "is_active": boolean
    }
    "ClauseUpsertRequest": {
      "alert_tipo"?: string | null
      "condition_key"?: string | null
      "condition_mode"?: "omit" | "block" | null
      "content_json": Record<string, unknown>
      "fixed_position"?: boolean
      "position": number
      "title": string
    }
    "ConnectRequest": {
      "credentials": string
      "display_name": string
      "organization_id": string
      "provider": string
      "scopes"?: Array<string> | null
      "server_url"?: string | null
      "user_id": string
    }
    "CreateBlockRequest": {
      "category": string
      "content": string
      "created_by"?: string | null
      "name": string
      "organization_id": string
      "tags"?: Array<string> | null
      "variables"?: Array<string> | null
    }
    "CreateTemplateRequest": {
      "created_by"?: string | null
      "description"?: string | null
      "document_type": string
      "footer_config"?: Record<string, unknown> | null
      "header_config"?: Record<string, unknown> | null
      "name": string
      "organization_id": string
      "page_config"?: Record<string, unknown> | null
    }
    "CreateVersionRequest": {
      "author_id"?: string | null
      "change_note"?: string | null
      "content": string
    }
    "DecisionRequest": {
      "action": string
      "admin_id": string
      "organization_id": string
    }
    "DecisionResponse": {
      "error"?: string | null
      "success": boolean
    }
    "DismissedAlert": {
      "reason"?: string | null
      "tipo": string
    }
    "DocumentEvidenceResponse": {
      "bbox"?: Record<string, unknown> | null
      "chunk_index"?: number | null
      "confidence"?: number | null
      "created_at"?: string | null
      "id": string
      "legal_document_id": string
      "legal_document_page_id"?: string | null
      "organization_id": string
      "project_id": string
      "snippet"?: string | null
      "snippet_hash": string
      "variable_resolution_id": string
    }
    "DocumentVariablesGroup": {
      "comprador"?: Record<string, unknown>
      "lote"?: Record<string, unknown>
      "mandato"?: Record<string, unknown>
      "matriz"?: Record<string, unknown>
      "personeria"?: Record<string, unknown>
      "sag"?: Record<string, unknown>
      "servidumbre"?: Record<string, unknown>
      "transaccion"?: Record<string, unknown>
      "vendedor"?: Record<string, unknown>
    }
    "EscrituraActiveCase": {
      "case_status": string
      "case_status_label": string
      "escritura_case_id": string
    }
    "EscrituraCaseCreateRequest": {
      "created_by"?: string | null
      "organization_id": string
      "project_id": string
      "warning_acknowledged"?: boolean
    }
    "EscrituraCaseSnapshotResponse": {
      "case_status": string
      "escritura_case_id": string
      "evidence_snapshot_count": number
      "readiness_status": string
      "variable_snapshot_count": number
    }
    "EscrituraReadinessResponse": {
      "active_case"?: components["schemas"]["EscrituraActiveCase"] | null
      "evidence_snapshot"?: Record<string, unknown>
      "gates"?: Array<components["schemas"]["ReadinessGateResponse"]>
      "lot_id": string
      "organization_id": string
      "project_id": string
      "readiness_status": string
      "variable_snapshot"?: Record<string, unknown>
    }
    "EscrituraTemplateDetail": {
      "clause_count"?: number
      "clauses"?: Array<components["schemas"]["TemplateClause"]>
      "document_type": string
      "id": string
      "name": string
      "published_at"?: string | null
      "status": "draft" | "published" | "retired"
      "updated_at"?: string | null
      "version": number
    }
    "EscrituraTemplateSummary": {
      "clause_count"?: number
      "document_type": string
      "id": string
      "name": string
      "published_at"?: string | null
      "status": "draft" | "published" | "retired"
      "updated_at"?: string | null
      "version": number
    }
    "Evidence": {
      "legal_document_id"?: string | null
      "page_number"?: number | null
      "snippet"?: string | null
    }
    "EvidencedValue": {
      "confidence"?: number | null
      "evidence"?: components["schemas"]["Evidence"] | null
      "value"?: string | null
      "verified"?: boolean | null
    }
    "GenerateMinutaRequest": {
      "generated_by": string
      "warning_acknowledged": boolean
    }
    "GenerateRequest": {
      "document_type"?: string
      "format"?: "pdf" | "docx"
      "generated_by"?: string | null
      "lot_id": string
      "missing_variables_accepted"?: boolean
      "organization_id": string
      "selected_recipients"?: Array<"vendedor" | "comprador">
      "template_id": string
    }
    "GenerateResponse": {
      "document_id": string
      "document_type": string
      "file_url": string
      "format": "pdf" | "docx"
      "lot_id": string
      "missing_variables_accepted": boolean
      "selected_recipients"?: Array<string>
      "template_id": string
      "version_number": number
    }
    "HTTPValidationError": {
      "detail"?: Array<components["schemas"]["ValidationError"]>
    }
    "InscriptionDetalle": {
      "anio"?: components["schemas"]["EvidencedValue"] | null
      "cbr"?: components["schemas"]["EvidencedValue"] | null
      "fojas"?: components["schemas"]["EvidencedValue"] | null
      "numero"?: components["schemas"]["EvidencedValue"] | null
    }
    "InscriptionEscritura": {
      "fecha"?: components["schemas"]["EvidencedValue"] | null
      "notaria_ciudad"?: components["schemas"]["EvidencedValue"] | null
      "notario"?: components["schemas"]["EvidencedValue"] | null
      "repertorio"?: components["schemas"]["EvidencedValue"] | null
    }
    "InscriptionObservacion": {
      "evidence"?: components["schemas"]["Evidence"] | null
      "tipo"?: string | null
    }
    "InscriptionRectificatoria": {
      "fecha"?: components["schemas"]["EvidencedValue"] | null
      "notario"?: components["schemas"]["EvidencedValue"] | null
      "repertorio"?: components["schemas"]["EvidencedValue"] | null
    }
    "InsertableVariable": {
      "category": string
      "category_label": string
      "key": string
      "label": string
    }
    "InvalidateCacheRequest": {
      "organization_id": string
    }
    "LegalDocumentArchiveResponse": {
      "extraction_status": string
      "legal_document_id": string
      "reanalysis_queued": boolean
      "title_analysis_superseded": boolean
      "title_reanalysis_recommended": boolean
    }
    "LegalDocumentListResponse": {
      "documents"?: Array<components["schemas"]["LegalDocumentResponse"]>
      "project_id"?: string | null
    }
    "LegalDocumentRegisterRequest": {
      "document_type": string
      "file_size_bytes": number
      "lot_id"?: string | null
      "mime_type": string
      "organization_id": string
      "original_filename": string
      "project_id": string
      "replaces_legal_document_id"?: string | null
      "sha256_hash": string
      "source_field"?: string | null
      "storage_bucket"?: string
      "storage_path": string
      "upload_source"?: string
      "uploaded_by"?: string | null
    }
    "LegalDocumentRegistrationQueuedResponse": {
      "extraction_status": string
      "ingestion_job_id": string
      "legal_document_id": string
      "version_number": number
    }
    "LegalDocumentResponse": {
      "created_at"?: string | null
      "document_type": string
      "extraction_status": string
      "file_size_bytes": number
      "id": string
      "lot_id"?: string | null
      "mime_type": string
      "organization_id": string
      "original_filename": string
      "project_id": string
      "sha256_hash"?: string | null
      "source_field"?: string | null
      "storage_bucket": string
      "storage_path": string
      "superseded_by"?: string | null
      "updated_at"?: string | null
      "upload_source": string
      "uploaded_by"?: string | null
      "version_number"?: number
    }
    "LegalDocumentRetryResponse": {
      "attempt_number": number
      "extraction_status": string
      "ingestion_job_id": string
      "legal_document_id": string
    }
    "LotLegalDataResponse": {
      "created_at"?: string | null
      "id": string
      "lot_id": string
      "lot_number"?: string | null
      "matching_score"?: number | null
      "matching_status": string
      "organization_id": string
      "project_id": string
      "reviewed_at"?: string | null
      "reviewed_by"?: string | null
      "role_status": string
      "sii_comuna"?: string | null
      "sii_definitive_role"?: string | null
      "sii_lot_number_normalized"?: string | null
      "sii_pre_role"?: string | null
      "sii_role_in_process_text"?: string | null
      "sii_role_matrix"?: string | null
      "sii_unit_name"?: string | null
      "source_document_label"?: string | null
      "source_legal_document_id"?: string | null
      "source_status"?: string | null
      "source_type"?: string | null
      "updated_at"?: string | null
    }
    "MarkReadResponse": {
      "read_at": string
      "success": boolean
    }
    "MatrizApproveRequest": {
      "approved_by": string
    }
    "MatrizCaseResponse": {
      "insertable_variables"?: Array<components["schemas"]["InsertableVariable"]>
      "matriz": components["schemas"]["MatrizView"]
    }
    "MatrizClauseCondition": {
      "active": boolean
      "key": string
      "mode": "omit" | "block"
    }
    "MatrizClauseOverride": {
      "content_json"?: Record<string, unknown> | null
      "disabled"?: boolean | null
      "title"?: string | null
    }
    "MatrizClauseView": {
      "alert_tipo"?: string | null
      "clause_key": string
      "condition"?: components["schemas"]["MatrizClauseCondition"] | null
      "content_json": Record<string, unknown>
      "disabled"?: boolean
      "fixed_position": boolean
      "omitted_reason"?: string | null
      "overridden"?: boolean
      "position": number
      "resolved_content"?: Record<string, unknown> | null
      "title": string
    }
    "MatrizEvidenceRef": {
      "legal_document_id"?: string | null
      "legal_document_page_id"?: string | null
      "page_number"?: number | null
      "snippet"?: string | null
    }
    "MatrizRejectRequest": {
      "reason": string
      "rejected_by": string
    }
    "MatrizSaveRequest": {
      "clause_order"?: Array<string>
      "clause_overrides"?: Record<string, components["schemas"]["MatrizClauseOverride"]>
      "version": number
    }
    "MatrizSubmitRequest": {
      "submitted_by": string
    }
    "MatrizTemplateRef": {
      "id": string
      "name": string
      "version": number
    }
    "MatrizView": {
      "approval_blockers"?: Array<components["schemas"]["ApprovalBlocker"]>
      "clause_order"?: Array<string>
      "clauses"?: Array<components["schemas"]["MatrizClauseView"]>
      "dismissed_alerts"?: Array<components["schemas"]["DismissedAlert"]>
      "escritura_case_id": string
      "id": string
      "project_id": string
      "resolution"?: components["schemas"]["ResolutionManifest"]
      "snapshot_stale"?: boolean
      "status": "draft" | "legal_review_pending" | "approved" | "superseded"
      "template": components["schemas"]["MatrizTemplateRef"]
      "version": number
    }
    "MetaChange": {
      "field": string
      "value": components["schemas"]["MetaValue"]
    }
    "MetaContact": {
      "profile": Record<string, unknown>
      "wa_id": string
    }
    "MetaEntry": {
      "changes": Array<components["schemas"]["MetaChange"]>
      "id": string
    }
    "MetaMessage": {
      "from": string
      "id": string
      "text"?: components["schemas"]["MetaText"] | null
      "timestamp": string
      "type"?: "text" | "image" | "audio" | "document" | "interactive" | "button" | "unknown"
    }
    "MetaText": {
      "body": string
    }
    "MetaValue": {
      "contacts"?: Array<components["schemas"]["MetaContact"]> | null
      "messages"?: Array<components["schemas"]["MetaMessage"]> | null
      "messaging_product": string
      "metadata": Record<string, unknown>
      "statuses"?: Array<Record<string, unknown>> | null
    }
    "MetaWebhookPayload": {
      "entry": Array<components["schemas"]["MetaEntry"]>
      "object": string
    }
    "MinutaGeneration": {
      "content_hash": string
      "download_url"?: string | null
      "escritura_case_id": string
      "generated_at": string
      "generated_by"?: string | null
      "id": string
      "matriz_id": string
      "matriz_version": number
      "snapshot_hash": string
      "storage_path": string
      "template_id": string
      "warning_acknowledged_at": string
      "warning_acknowledged_by": string
    }
    "MinutaGenerationListResponse": {
      "generations"?: Array<components["schemas"]["MinutaGeneration"]>
    }
    "NotificationCounts": {
      "approved": number
      "pending": number
      "rejected": number
      "unread": number
    }
    "NotificationDecisionRequest": {
      "action": "approve" | "reject"
      "approval_id": string
    }
    "NotificationDecisionResponse": {
      "code"?: string | null
      "error"?: string | null
      "status"?: string | null
      "success": boolean
    }
    "NotificationItem": {
      "approval_id": string
      "can_decide": boolean
      "client_name": string
      "created_at": string
      "decided_at"?: string | null
      "id": string
      "lot_label": string
      "project_name": string
      "read_at"?: string | null
      "request_type": string
      "status": string
      "vendor_name": string
    }
    "NotificationListResponse": {
      "counts": components["schemas"]["NotificationCounts"]
      "items": Array<components["schemas"]["NotificationItem"]>
    }
    "PreviewRequest": {
      "lot_id": string
      "organization_id": string
      "template_id": string
    }
    "PreviewResponse": {
      "html": string
    }
    "PropertyDeslindes": {
      "norte"?: components["schemas"]["EvidencedValue"] | null
      "oriente"?: components["schemas"]["EvidencedValue"] | null
      "poniente"?: components["schemas"]["EvidencedValue"] | null
      "sur"?: components["schemas"]["EvidencedValue"] | null
    }
    "PropertyIdentity": {
      "comuna"?: components["schemas"]["EvidencedValue"] | null
      "deslindes"?: components["schemas"]["PropertyDeslindes"] | null
      "nombre_predio"?: components["schemas"]["EvidencedValue"] | null
      "provincia"?: components["schemas"]["EvidencedValue"] | null
      "region"?: components["schemas"]["EvidencedValue"] | null
      "rol_avaluo"?: components["schemas"]["EvidencedValue"] | null
      "superficie_texto"?: components["schemas"]["EvidencedValue"] | null
      "ubicacion"?: components["schemas"]["EvidencedValue"] | null
    }
    "PropietarioActual": {
      "cuota"?: string | null
      "domicilio"?: components["schemas"]["EvidencedValue"] | null
      "estado_civil"?: components["schemas"]["EvidencedValue"] | null
      "nacionalidad"?: components["schemas"]["EvidencedValue"] | null
      "nombre"?: components["schemas"]["EvidencedValue"] | null
      "profesion"?: components["schemas"]["EvidencedValue"] | null
      "requiere_personeria"?: boolean | null
      "rut"?: components["schemas"]["EvidencedValue"] | null
      "tratamiento"?: components["schemas"]["EvidencedValue"] | null
    }
    "ReadinessGateResponse": {
      "blocking_variables"?: Array<string>
      "gate": string
      "status": string
      "warnings"?: Array<string>
    }
    "RegisterBotRequest": {
      "bot_token": string
      "organization_id": string
    }
    "ReservationPayload": {
      "cliente_nombre": string
      "cliente_run": string
      "fecha_firma"?: string | null
      "notaria"?: string | null
      "valor_reserva": number
    }
    "ReservationRequest": {
      "lot_id": string
      "organization_id": string
      "payload": components["schemas"]["ReservationPayload"]
      "vendor_id": string
      "vendor_name": string
      "vendor_phone": string
      "vendor_platform": string
    }
    "ReservationResponse": {
      "approval_id": string
      "message"?: string
      "status"?: string
    }
    "ResolutionManifest": {
      "blocks"?: Array<components["schemas"]["BlockResolution"]>
      "missing_count"?: number
      "tokens"?: Array<components["schemas"]["TokenResolution"]>
    }
    "RoleManualOverrideRequest": {
      "matching_status"?: string
      "reason": string
      "reviewed_by"?: string | null
      "role_status": string
      "sii_comuna"?: string | null
      "sii_definitive_role"?: string | null
      "sii_lot_number_normalized"?: string | null
      "sii_pre_role"?: string | null
      "sii_role_in_process_text"?: string | null
      "sii_role_matrix"?: string | null
      "sii_role_record"?: Record<string, unknown> | null
      "sii_unit_name"?: string | null
      "source_legal_document_id"?: string | null
    }
    "RoleMatchingInventoryResponse": {
      "certificate_summary"?: components["schemas"]["SiiRoleCertificateSummary"] | null
      "lots"?: Array<components["schemas"]["LotLegalDataResponse"]>
      "project_id": string
      "review_counts"?: Record<string, number>
      "summary"?: Record<string, number>
    }
    "SalePayload": {
      "cliente_nombre": string
      "cliente_run": string
      "fecha_firma"?: string | null
      "notaria"?: string | null
      "valor_final": number
    }
    "SaleRequest": {
      "lot_id": string
      "organization_id": string
      "payload": components["schemas"]["SalePayload"]
      "previous_lot_state"?: "disponible" | "reservado" | null
      "sale_mode"?: "direct" | "reserved" | null
      "vendor_id": string
      "vendor_name": string
      "vendor_phone": string
      "vendor_platform": string
    }
    "SandboxRequest": {
      "organization_id": string
      "prompt_content": string
      "test_message": string
    }
    "SiiRoleCertificateSummary": {
      "active_certificate_count"?: number
      "ambiguous_matrix_role_count"?: number
      "comunas"?: Array<string>
      "extracted_unit_count"?: number
      "manual_review_count"?: number
      "matched_count"?: number
      "missing_count"?: number
      "ocr_required"?: boolean | null
      "role_matrices"?: Array<string>
      "source_legal_document_ids"?: Array<string>
      "superseded_certificate_count"?: number
      "text_source"?: string | null
    }
    "StageOperationalResult": {
      "missing"?: Array<string>
      "proposed"?: Array<string>
      "protected"?: Array<string>
      "skipped_same_hash"?: Array<string>
      "superseded"?: Array<string>
    }
    "TelegramTokenRequest": {
      "organization_id"?: string | null
      "profile_id": string
    }
    "TelegramTokenResponse": {
      "bot_username": string
      "deep_link": string
      "token": string
    }
    "TemplateClause": {
      "alert_tipo"?: string | null
      "clause_key": string
      "condition_key"?: string | null
      "condition_mode"?: "omit" | "block" | null
      "content_json": Record<string, unknown>
      "fixed_position"?: boolean
      "id"?: string | null
      "position": number
      "title": string
    }
    "TemplateCreateRequest": {
      "clone_from_template_id"?: string | null
      "document_type"?: string
      "name": string
    }
    "TemplateListResponse": {
      "insertable_variables"?: Array<components["schemas"]["InsertableVariable"]>
      "templates"?: Array<components["schemas"]["EscrituraTemplateSummary"]>
    }
    "TemplatePublishRequest": {
      "published_by": string
    }
    "TitleAlert": {
      "detalle"?: string | null
      "evidence"?: components["schemas"]["Evidence"] | null
      "reason"?: string | null
      "resolution"?: string
      "tipo": string
    }
    "TitleAlertResolveRequest": {
      "reason": string
      "resolution": string
      "resolved_by": string
    }
    "TitleAnalysis": {
      "alertas"?: Array<components["schemas"]["TitleAlert"]>
      "inscripciones"?: Array<components["schemas"]["TitleInscription"]>
      "property_identity"?: components["schemas"]["PropertyIdentity"] | null
      "propietarios_actuales"?: Array<components["schemas"]["PropietarioActual"]>
      "structure_type"?: string | null
    }
    "TitleAnalysisNarrative": {
      "comparecencia"?: components["schemas"]["TitleAnalysisNarrativeBlock"] | null
      "primero"?: components["schemas"]["TitleAnalysisNarrativeBlock"] | null
    }
    "TitleAnalysisNarrativeBlock": {
      "edited"?: string | null
      "effective"?: string | null
      "generated"?: string | null
    }
    "TitleAnalysisPendingReview": {
      "path": string
      "state"?: string
    }
    "TitleAnalysisReanalyzeResponse": {
      "analysis_id": string
      "queued": boolean
      "status": string
    }
    "TitleAnalysisResponseData": {
      "alerts"?: Array<components["schemas"]["TitleAlert"]>
      "analysis"?: components["schemas"]["TitleAnalysis"] | null
      "approved_at"?: string | null
      "approved_by"?: string | null
      "id": string
      "narrative"?: components["schemas"]["TitleAnalysisNarrative"] | null
      "pending_review"?: Array<components["schemas"]["TitleAnalysisPendingReview"]>
      "run"?: components["schemas"]["TitleAnalysisRunDetails"] | null
      "source_documents"?: Array<components["schemas"]["TitleAnalysisSourceDocument"]>
      "status": string
      "structure_type"?: string | null
      "verification"?: components["schemas"]["TitleAnalysisVerification"] | null
    }
    "TitleAnalysisRunDetails": {
      "created_at"?: string | null
      "duration_ms"?: number | null
      "extractor_name": string
      "model_name": string
      "prompt_version": string
    }
    "TitleAnalysisSourceDocument": {
      "document_type": string
      "filename"?: string | null
      "legal_document_id": string
      "version"?: number
    }
    "TitleAnalysisVerification": {
      "agent_notes"?: Array<string>
      "block_checks"?: Record<string, components["schemas"]["TitleBlockCheck"]> | null
      "failures"?: Array<components["schemas"]["TitleAnalysisVerificationFailure"]>
      "unverified_count"?: number
      "verified_count"?: number
    }
    "TitleAnalysisVerificationFailure": {
      "path": string
      "proposed_snippet"?: string | null
      "reason": string
    }
    "TitleApproveRequest": {
      "approved_by": string
    }
    "TitleBlockCheck": {
      "issues"?: Array<components["schemas"]["TitleBlockCheckIssue"]>
      "ok"?: boolean
    }
    "TitleBlockCheckIssue": {
      "hecho": string
      "motivo": string
    }
    "TitleCaseResponse": {
      "analysis"?: components["schemas"]["TitleAnalysisResponseData"] | null
    }
    "TitleInscription": {
      "adquirentes"?: Array<components["schemas"]["Adquirente"]>
      "antecesor"?: components["schemas"]["Antecesor"] | null
      "escritura"?: components["schemas"]["InscriptionEscritura"] | null
      "inscripcion"?: components["schemas"]["InscriptionDetalle"] | null
      "observaciones"?: Array<components["schemas"]["InscriptionObservacion"]>
      "orden": number
      "rectificatorias"?: Array<components["schemas"]["InscriptionRectificatoria"]>
      "tipo_adquisicion": string
    }
    "TitleNarrativeUpdateRequest": {
      "block": string
      "edited_by": string
      "edited_text": string
      "reason": string
    }
    "TokenResolution": {
      "category"?: string | null
      "category_label"?: string | null
      "evidence_refs"?: Array<components["schemas"]["MatrizEvidenceRef"]>
      "label"?: string | null
      "source_label"?: string | null
      "source_type"?: string | null
      "state"?: string | null
      "status": "resolved" | "missing" | "blocked"
      "value_text"?: string | null
      "variableKey": string
    }
    "UpdateBlockRequest": {
      "category"?: string | null
      "content"?: string | null
      "is_active"?: boolean | null
      "name"?: string | null
      "tags"?: Array<string> | null
      "variables"?: Array<string> | null
    }
    "ValidationError": {
      "ctx"?: Record<string, unknown>
      "input"?: unknown
      "loc": Array<string | number>
      "msg": string
      "type": string
    }
    "VariableInventoryResponse": {
      "groups"?: Record<string, Array<components["schemas"]["VariableResolutionResponse"]>>
      "lot_id"?: string | null
      "project_id": string
      "summary"?: Record<string, number>
    }
    "VariableResolutionResponse": {
      "approval_required"?: boolean
      "confidence"?: number | null
      "correction_reason"?: string | null
      "created_at"?: string | null
      "escritura_case_id"?: string | null
      "evidence"?: Array<components["schemas"]["DocumentEvidenceResponse"]>
      "extractor_name"?: string | null
      "id": string
      "lot_id"?: string | null
      "organization_id": string
      "project_id": string
      "reviewed_at"?: string | null
      "reviewed_by"?: string | null
      "source_ref"?: Record<string, unknown>
      "source_type": string
      "state": string
      "superseded_by"?: string | null
      "updated_at"?: string | null
      "value_json"?: Record<string, unknown> | Array<unknown> | null
      "value_text"?: string | null
      "variable_group": string
      "variable_key": string
    }
    "VariableReviewResponse": {
      "audit_event_id": string
      "reviewed_at"?: string | null
      "reviewed_by"?: string | null
      "state": string
      "variable_resolution_id": string
    }
    "VariableStatusResponse": {
      "available"?: Array<string>
      "missing"?: Array<string>
      "sources"?: Record<string, string>
      "variables": components["schemas"]["DocumentVariablesGroup"]
    }
    "VariableUpdateRequest": {
      "action": string
      "correction_reason"?: string | null
      "evidence_ids"?: Array<string>
      "evidence_policy"?: string
      "reviewed_by"?: string | null
      "state"?: string | null
      "value_json"?: Record<string, unknown> | Array<unknown> | null
      "value_text"?: string | null
    }
  }
}

export interface operations {
  "requestReservationApproval": {
    method: "POST"
    path: "/api/v1/approvals/request-reservation"
    requestBody: components["schemas"]["ReservationRequest"]
    response: components["schemas"]["ReservationResponse"]
  }
  "requestSaleApproval": {
    method: "POST"
    path: "/api/v1/approvals/request-sale"
    requestBody: components["schemas"]["SaleRequest"]
    response: components["schemas"]["ReservationResponse"]
  }
  "getApprovalRequest": {
    method: "GET"
    path: "/api/v1/approvals/{approval_id}"
    requestBody: never
    response: components["schemas"]["ApprovalRequestDetailResponse"]
  }
  "decideApprovalRequest": {
    method: "POST"
    path: "/api/v1/approvals/{approval_id}/decide"
    requestBody: components["schemas"]["DecisionRequest"]
    response: components["schemas"]["DecisionResponse"]
  }
  "register_bot_api_v1_bots_register_post": {
    method: "POST"
    path: "/api/v1/bots/register"
    requestBody: components["schemas"]["RegisterBotRequest"]
    response: components["schemas"]["BotResponse"]
  }
  "delete_bot_api_v1_bots__org_id__delete": {
    method: "DELETE"
    path: "/api/v1/bots/{org_id}"
    requestBody: never
    response: void
  }
  "get_bot_api_v1_bots__org_id__get": {
    method: "GET"
    path: "/api/v1/bots/{org_id}"
    requestBody: never
    response: components["schemas"]["BotResponse"] | null
  }
  "list_blocks_api_v1_documents_blocks_get": {
    method: "GET"
    path: "/api/v1/documents/blocks"
    requestBody: never
    response: Array<Record<string, unknown>>
  }
  "create_block_api_v1_documents_blocks_post": {
    method: "POST"
    path: "/api/v1/documents/blocks"
    requestBody: components["schemas"]["CreateBlockRequest"]
    response: Record<string, unknown>
  }
  "update_block_api_v1_documents_blocks__block_id__put": {
    method: "PUT"
    path: "/api/v1/documents/blocks/{block_id}"
    requestBody: components["schemas"]["UpdateBlockRequest"]
    response: Record<string, unknown>
  }
  "generateDocument": {
    method: "POST"
    path: "/api/v1/documents/generate"
    requestBody: components["schemas"]["GenerateRequest"]
    response: components["schemas"]["GenerateResponse"]
  }
  "list_generated_documents_api_v1_documents_generated_get": {
    method: "GET"
    path: "/api/v1/documents/generated"
    requestBody: never
    response: Array<Record<string, unknown>>
  }
  "previewDocument": {
    method: "POST"
    path: "/api/v1/documents/preview"
    requestBody: components["schemas"]["PreviewRequest"]
    response: components["schemas"]["PreviewResponse"]
  }
  "list_templates_api_v1_documents_templates_get": {
    method: "GET"
    path: "/api/v1/documents/templates"
    requestBody: never
    response: Array<Record<string, unknown>>
  }
  "create_template_api_v1_documents_templates_post": {
    method: "POST"
    path: "/api/v1/documents/templates"
    requestBody: components["schemas"]["CreateTemplateRequest"]
    response: Record<string, unknown>
  }
  "get_template_blocks_api_v1_documents_templates__template_id__blocks_get": {
    method: "GET"
    path: "/api/v1/documents/templates/{template_id}/blocks"
    requestBody: never
    response: Array<Record<string, unknown>>
  }
  "add_block_to_template_api_v1_documents_templates__template_id__blocks_post": {
    method: "POST"
    path: "/api/v1/documents/templates/{template_id}/blocks"
    requestBody: components["schemas"]["AddBlockToTemplateRequest"]
    response: Record<string, unknown>
  }
  "remove_block_from_template_api_v1_documents_templates__template_id__blocks__item_id__delete": {
    method: "DELETE"
    path: "/api/v1/documents/templates/{template_id}/blocks/{item_id}"
    requestBody: never
    response: void
  }
  "get_variables_api_v1_documents_variables__lot_id__get": {
    method: "GET"
    path: "/api/v1/documents/variables/{lot_id}"
    requestBody: never
    response: components["schemas"]["VariableStatusResponse"]
  }
  "create_escritura_case_api_v1_escritura_cases_lots__lot_id__post": {
    method: "POST"
    path: "/api/v1/escritura-cases/lots/{lot_id}"
    requestBody: components["schemas"]["EscrituraCaseCreateRequest"]
    response: components["schemas"]["EscrituraCaseSnapshotResponse"]
  }
  "get_escritura_readiness_api_v1_escritura_cases_lots__lot_id__readiness_get": {
    method: "GET"
    path: "/api/v1/escritura-cases/lots/{lot_id}/readiness"
    requestBody: never
    response: components["schemas"]["EscrituraReadinessResponse"]
  }
  "stage_operational_variables_api_v1_escritura_cases__escritura_case_id__stage_operational_post": {
    method: "POST"
    path: "/api/v1/escritura-cases/{escritura_case_id}/stage-operational"
    requestBody: never
    response: components["schemas"]["StageOperationalResult"]
  }
  "get_case_matriz_api_v1_escritura_matrices_case__escritura_case_id__get": {
    method: "GET"
    path: "/api/v1/escritura-matrices/case/{escritura_case_id}"
    requestBody: never
    response: components["schemas"]["MatrizCaseResponse"]
  }
  "list_case_generations_api_v1_escritura_matrices_case__escritura_case_id__generations_get": {
    method: "GET"
    path: "/api/v1/escritura-matrices/case/{escritura_case_id}/generations"
    requestBody: never
    response: components["schemas"]["MinutaGenerationListResponse"]
  }
  "save_matriz_api_v1_escritura_matrices__matriz_id__put": {
    method: "PUT"
    path: "/api/v1/escritura-matrices/{matriz_id}"
    requestBody: components["schemas"]["MatrizSaveRequest"]
    response: components["schemas"]["MatrizCaseResponse"]
  }
  "approve_matriz_api_v1_escritura_matrices__matriz_id__approve_post": {
    method: "POST"
    path: "/api/v1/escritura-matrices/{matriz_id}/approve"
    requestBody: components["schemas"]["MatrizApproveRequest"]
    response: components["schemas"]["MatrizCaseResponse"]
  }
  "generate_minuta_api_v1_escritura_matrices__matriz_id__generate_post": {
    method: "POST"
    path: "/api/v1/escritura-matrices/{matriz_id}/generate"
    requestBody: components["schemas"]["GenerateMinutaRequest"]
    response: components["schemas"]["MinutaGeneration"]
  }
  "reject_matriz_api_v1_escritura_matrices__matriz_id__reject_post": {
    method: "POST"
    path: "/api/v1/escritura-matrices/{matriz_id}/reject"
    requestBody: components["schemas"]["MatrizRejectRequest"]
    response: components["schemas"]["MatrizCaseResponse"]
  }
  "submit_matriz_api_v1_escritura_matrices__matriz_id__submit_post": {
    method: "POST"
    path: "/api/v1/escritura-matrices/{matriz_id}/submit"
    requestBody: components["schemas"]["MatrizSubmitRequest"]
    response: components["schemas"]["MatrizCaseResponse"]
  }
  "list_escritura_templates_api_v1_escritura_templates_get": {
    method: "GET"
    path: "/api/v1/escritura-templates"
    requestBody: never
    response: components["schemas"]["TemplateListResponse"]
  }
  "create_escritura_template_api_v1_escritura_templates_post": {
    method: "POST"
    path: "/api/v1/escritura-templates"
    requestBody: components["schemas"]["TemplateCreateRequest"]
    response: components["schemas"]["EscrituraTemplateDetail"]
  }
  "get_escritura_template_api_v1_escritura_templates__template_id__get": {
    method: "GET"
    path: "/api/v1/escritura-templates/{template_id}"
    requestBody: never
    response: components["schemas"]["EscrituraTemplateDetail"]
  }
  "upsert_escritura_template_clause_api_v1_escritura_templates__template_id__clauses_put": {
    method: "PUT"
    path: "/api/v1/escritura-templates/{template_id}/clauses"
    requestBody: components["schemas"]["ClauseUpsertRequest"]
    response: components["schemas"]["EscrituraTemplateDetail"]
  }
  "upsert_escritura_template_clause_api_v1_escritura_templates__template_id__clauses__clause_key__put": {
    method: "PUT"
    path: "/api/v1/escritura-templates/{template_id}/clauses/{clause_key}"
    requestBody: components["schemas"]["ClauseUpsertRequest"]
    response: components["schemas"]["EscrituraTemplateDetail"]
  }
  "publish_escritura_template_api_v1_escritura_templates__template_id__publish_post": {
    method: "POST"
    path: "/api/v1/escritura-templates/{template_id}/publish"
    requestBody: components["schemas"]["TemplatePublishRequest"]
    response: components["schemas"]["EscrituraTemplateDetail"]
  }
  "health_check_api_v1_health_get": {
    method: "GET"
    path: "/api/v1/health"
    requestBody: never
    response: Record<string, string>
  }
  "list_integrations_api_v1_integrations__get": {
    method: "GET"
    path: "/api/v1/integrations/"
    requestBody: never
    response: void
  }
  "connect_integration_api_v1_integrations_connect_post": {
    method: "POST"
    path: "/api/v1/integrations/connect"
    requestBody: components["schemas"]["ConnectRequest"]
    response: void
  }
  "revoke_integration_api_v1_integrations__connection_id__delete": {
    method: "DELETE"
    path: "/api/v1/integrations/{connection_id}"
    requestBody: never
    response: void
  }
  "test_integration_api_v1_integrations__connection_id__test_post": {
    method: "POST"
    path: "/api/v1/integrations/{connection_id}/test"
    requestBody: never
    response: void
  }
  "list_project_legal_documents_api_v1_legal_documents_project__project_id__get": {
    method: "GET"
    path: "/api/v1/legal-documents/project/{project_id}"
    requestBody: never
    response: components["schemas"]["LegalDocumentListResponse"]
  }
  "register_legal_document_api_v1_legal_documents_register_post": {
    method: "POST"
    path: "/api/v1/legal-documents/register"
    requestBody: components["schemas"]["LegalDocumentRegisterRequest"]
    response: components["schemas"]["LegalDocumentRegistrationQueuedResponse"]
  }
  "archive_legal_document_api_v1_legal_documents__legal_document_id__archive_post": {
    method: "POST"
    path: "/api/v1/legal-documents/{legal_document_id}/archive"
    requestBody: never
    response: components["schemas"]["LegalDocumentArchiveResponse"]
  }
  "retry_legal_document_ingestion_api_v1_legal_documents__legal_document_id__retry_post": {
    method: "POST"
    path: "/api/v1/legal-documents/{legal_document_id}/retry"
    requestBody: never
    response: components["schemas"]["LegalDocumentRetryResponse"]
  }
  "update_lot_legal_role_api_v1_legal_roles_lots__lot_id__patch": {
    method: "PATCH"
    path: "/api/v1/legal-roles/lots/{lot_id}"
    requestBody: components["schemas"]["RoleManualOverrideRequest"]
    response: components["schemas"]["LotLegalDataResponse"]
  }
  "get_project_legal_roles_api_v1_legal_roles_project__project_id__matches_get": {
    method: "GET"
    path: "/api/v1/legal-roles/project/{project_id}/matches"
    requestBody: never
    response: components["schemas"]["RoleMatchingInventoryResponse"]
  }
  "get_project_title_case_api_v1_legal_titles_project__project_id__get": {
    method: "GET"
    path: "/api/v1/legal-titles/project/{project_id}"
    requestBody: never
    response: components["schemas"]["TitleCaseResponse"]
  }
  "reanalyze_project_title_api_v1_legal_titles_project__project_id__reanalyze_post": {
    method: "POST"
    path: "/api/v1/legal-titles/project/{project_id}/reanalyze"
    requestBody: never
    response: components["schemas"]["TitleAnalysisReanalyzeResponse"]
  }
  "resolve_title_alert_api_v1_legal_titles__analysis_id__alerts__alert_index__resolve_post": {
    method: "POST"
    path: "/api/v1/legal-titles/{analysis_id}/alerts/{alert_index}/resolve"
    requestBody: components["schemas"]["TitleAlertResolveRequest"]
    response: components["schemas"]["TitleAlert"]
  }
  "approve_title_case_api_v1_legal_titles__analysis_id__approve_post": {
    method: "POST"
    path: "/api/v1/legal-titles/{analysis_id}/approve"
    requestBody: components["schemas"]["TitleApproveRequest"]
    response: components["schemas"]["TitleAnalysisResponseData"]
  }
  "update_title_narrative_api_v1_legal_titles__analysis_id__narrative_patch": {
    method: "PATCH"
    path: "/api/v1/legal-titles/{analysis_id}/narrative"
    requestBody: components["schemas"]["TitleNarrativeUpdateRequest"]
    response: components["schemas"]["TitleAnalysisNarrative"]
  }
  "get_project_legal_variables_api_v1_legal_variables_project__project_id__get": {
    method: "GET"
    path: "/api/v1/legal-variables/project/{project_id}"
    requestBody: never
    response: components["schemas"]["VariableInventoryResponse"]
  }
  "update_legal_variable_api_v1_legal_variables__variable_resolution_id__patch": {
    method: "PATCH"
    path: "/api/v1/legal-variables/{variable_resolution_id}"
    requestBody: components["schemas"]["VariableUpdateRequest"]
    response: components["schemas"]["VariableReviewResponse"]
  }
  "listNotifications": {
    method: "GET"
    path: "/api/v1/notifications/"
    requestBody: never
    response: components["schemas"]["NotificationListResponse"]
  }
  "decideNotificationApproval": {
    method: "POST"
    path: "/api/v1/notifications/{approval_id}/decide"
    requestBody: components["schemas"]["NotificationDecisionRequest"]
    response: components["schemas"]["NotificationDecisionResponse"]
  }
  "markNotificationRead": {
    method: "POST"
    path: "/api/v1/notifications/{notification_id}/read"
    requestBody: never
    response: components["schemas"]["MarkReadResponse"]
  }
  "list_prompts_api_v1_prompts__get": {
    method: "GET"
    path: "/api/v1/prompts/"
    requestBody: never
    response: void
  }
  "sandbox_prompt_api_v1_prompts_sandbox_post": {
    method: "POST"
    path: "/api/v1/prompts/sandbox"
    requestBody: components["schemas"]["SandboxRequest"]
    response: void
  }
  "activate_version_api_v1_prompts__prompt_id__activate__version_id__put": {
    method: "PUT"
    path: "/api/v1/prompts/{prompt_id}/activate/{version_id}"
    requestBody: never
    response: void
  }
  "list_versions_api_v1_prompts__prompt_id__versions_get": {
    method: "GET"
    path: "/api/v1/prompts/{prompt_id}/versions"
    requestBody: never
    response: void
  }
  "create_version_api_v1_prompts__prompt_id__versions_post": {
    method: "POST"
    path: "/api/v1/prompts/{prompt_id}/versions"
    requestBody: components["schemas"]["CreateVersionRequest"]
    response: void
  }
  "invalidate_cache_api_v1_skills_invalidate_cache_post": {
    method: "POST"
    path: "/api/v1/skills/invalidate-cache"
    requestBody: components["schemas"]["InvalidateCacheRequest"]
    response: void
  }
  "generate_telegram_vincule_token_api_v1_users_telegram_token_post": {
    method: "POST"
    path: "/api/v1/users/telegram-token"
    requestBody: components["schemas"]["TelegramTokenRequest"]
    response: components["schemas"]["TelegramTokenResponse"]
  }
  "verify_meta_webhook_api_v1_webhook_meta_get": {
    method: "GET"
    path: "/api/v1/webhook/meta"
    requestBody: never
    response: void
  }
  "receive_meta_webhook_api_v1_webhook_meta_post": {
    method: "POST"
    path: "/api/v1/webhook/meta"
    requestBody: components["schemas"]["MetaWebhookPayload"]
    response: void
  }
  "receive_telegram_webhook_api_v1_webhook_telegram__org_id__post": {
    method: "POST"
    path: "/api/v1/webhook/telegram/{org_id}"
    requestBody: never
    response: void
  }
}

export type OperationRequestBody<K extends keyof operations> = operations[K]["requestBody"]
export type OperationResponse<K extends keyof operations> = operations[K]["response"]
