"""Export the FastAPI OpenAPI contract and generated TypeScript types.

Run from `apps/api/`:

    ./venv/bin/python scripts/export_openapi_contract.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

BACKEND_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND_ROOT))

from main import app


ROOT = Path(__file__).resolve().parents[3]
OPENAPI_PATH = ROOT / "packages/contracts/openapi/plotify-chat.v1.json"
TYPES_PATH = ROOT / "apps/web/src/lib/services/plotify-chat.generated.ts"


def _schema_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _schema_to_ts(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return f'components["schemas"]["{_schema_name(schema["$ref"])}"]'

    if "const" in schema:
        return _literal(schema["const"])

    if "enum" in schema:
        values = [_literal(v) for v in schema["enum"]]
        return " | ".join(values) if values else "never"

    if "anyOf" in schema:
        return " | ".join(_schema_to_ts(item) for item in schema["anyOf"])

    if "oneOf" in schema:
        return " | ".join(_schema_to_ts(item) for item in schema["oneOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_schema_to_ts({"type": item}) for item in schema_type)

    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        return f"Array<{_schema_to_ts(schema.get('items', {}))}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties") or {}
        required = set(schema.get("required") or [])
        if not properties:
            additional = schema.get("additionalProperties")
            if isinstance(additional, dict):
                return f"Record<string, {_schema_to_ts(additional)}>"
            return "Record<string, unknown>"

        lines = ["{"]
        for name, prop_schema in sorted(properties.items()):
            optional = "" if name in required else "?"
            lines.append(f"    {json.dumps(name)}{optional}: {_schema_to_ts(prop_schema)}")
        lines.append("  }")
        return "\n  ".join(lines)

    return "unknown"


def _response_schema(operation: dict[str, Any], status_code: str) -> str:
    response = operation.get("responses", {}).get(status_code)
    if not response:
        return "never"
    content = response.get("content", {})
    json_content = content.get("application/json", {})
    schema = json_content.get("schema")
    return _schema_to_ts(schema) if schema else "void"


def _request_schema(operation: dict[str, Any]) -> str:
    body = operation.get("requestBody")
    if not body:
        return "never"
    content = body.get("content", {})
    json_content = content.get("application/json", {})
    schema = json_content.get("schema")
    return _schema_to_ts(schema) if schema else "never"


def _generate_types(openapi: dict[str, Any]) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    schema_lines = ["export interface components {", "  schemas: {"]
    for name, schema in sorted(schemas.items()):
        schema_lines.append(f'    "{name}": {_schema_to_ts(schema)}')
    schema_lines.extend(["  }", "}"])

    operation_lines = ["export interface operations {"]
    for path, path_item in sorted(openapi.get("paths", {}).items()):
        for method, operation in sorted(path_item.items()):
            if method not in {"get", "post", "put", "delete", "patch"}:
                continue
            operation_id = operation.get("operationId")
            if not operation_id:
                continue
            success_code = next(
                (
                    code
                    for code in ("200", "201", "202", "204")
                    if code in operation.get("responses", {})
                ),
                "200",
            )
            operation_lines.append(f'  "{operation_id}": {{')
            operation_lines.append(f'    method: "{method.upper()}"')
            operation_lines.append(f'    path: "{path}"')
            operation_lines.append(f"    requestBody: {_request_schema(operation)}")
            operation_lines.append(f"    response: {_response_schema(operation, success_code)}")
            operation_lines.append("  }")
    operation_lines.append("}")

    return "\n".join(
        [
            "/* eslint-disable */",
            "// Generated by apps/api/scripts/export_openapi_contract.py.",
            "// Do not edit manually.",
            "",
            *schema_lines,
            "",
            *operation_lines,
            "",
            "export type OperationRequestBody<K extends keyof operations> = operations[K][\"requestBody\"]",
            "export type OperationResponse<K extends keyof operations> = operations[K][\"response\"]",
            "",
        ]
    )


def main() -> None:
    openapi = app.openapi()
    OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
    TYPES_PATH.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_PATH.write_text(
        json.dumps(openapi, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    TYPES_PATH.write_text(_generate_types(openapi), encoding="utf-8")
    print(f"Wrote {OPENAPI_PATH.relative_to(ROOT)}")
    print(f"Wrote {TYPES_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
